# Generated by Django 5.0.2 on 2024-02-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, null=True, unique=True, verbose_name='Имя')),
                ('role', models.CharField(choices=[('client', 'Client'), ('organization', 'Organization')], verbose_name='Роль')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
                ('time', models.IntegerField(choices=[(0, 'не напоминать'), (1, 'за один час'), (3, 'за три часа'), (12, 'за двенадцать часов')], default=1, verbose_name='Напомнить за')),
                ('message', models.TextField(verbose_name='Напоминание')),
            ],
        ),
    ]
