# Generated by Django 5.0.2 on 2024-02-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_records_remove_reminder_name_remove_reminder_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordings',
            name='reminder',
        ),
        migrations.DeleteModel(
            name='Records',
        ),
        migrations.DeleteModel(
            name='Recordings',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
