# Generated by Django 5.0.2 on 2024-02-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='number_clients',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Количество клиентов'),
        ),
    ]
