

###
POST http://0.0.0.0:8000/event/
Content-Type: application/x-www-form-urlencoded

name = afgdaasd &
date = 2000-12-10 12:12

###
GET http://0.0.0.0:8000/event?event_id=51

###
POST http://0.0.0.0:8000/record/
Content-Type: application/x-www-form-urlencoded

user_id = 12 &
event_id = 599 &
reminder_time = 1

